### ISSUE TITLE
Please add support for ed25519 keys

### ISSUE THREAD

**Issue by kiryanov** [FarGroup/Far-NetBox#18]
Please add support for ed25519 keys. Both PuTTY and WinSCP have built-in support for ed25519 keys for quite a while now and NetBox heeds to catch up. ed25519 is replacing RSA and ECDSA in more and more places and a lack of support from NetBox becomes a real inconvenience.

**Comment by SignFinder** [comment]
Hi team,
It is a really pity to have this bug :-( could you kindly pay attention to this issue.

**Comment by alabuzhev** [comment]
Moved to https://github.com/michaellukashov/Far-NetBox/issues/385
