### ISSUE TITLE
Daylight Saving Time bug

### ISSUE THREAD

**Issue by viccpp** [FarGroup/Far-NetBox#35]
File saved from the editor has a timestamp `NOW - 1 hour` when daylight saving time is used on the client.

I use SCP file protocol and "Upload after every save" flag if it makes any difference.

**Comment by viccpp** [comment]
https://github.com/michaellukashov/Far-NetBox/issues/289

**Comment by viccpp** [comment]
Can be worked around by setting "Preserve remote timestamp (Unix)" in `Edit session` -> `Environment`.

But both client and server are in the same timezone. I think such configurations must "just work" out of the box.

**Comment by alabuzhev** [comment]
Moved to https://github.com/michaellukashov/Far-NetBox/issues/391
