### ISSUE TITLE
FAR Manager crash after SSH chmod

### ISSUE THREAD

**Issue by MorthimerMcMare** [FarGroup/Far-NetBox#37]
Far v3.0.6060.0 x64 (a834cf2) with NetBox 2.4.545.5. Crashed when I tried to change directory permissions on the remote Linux machine to "r-- r-- r--" (444) via "Ctrl + A".

"bug_report.txt" and "far.mdmp": [Far_20230411_144237973_11828_crash_info.zip](https://github.com/FarGroup/Far-NetBox/files/11201895/Far_20230411_144237973_11828_crash_info.zip).

**Comment by alabuzhev** [comment]
Moved to https://github.com/michaellukashov/Far-NetBox/issues/393
