### ISSUE TITLE
Interface update required

### ISSUE THREAD

**Issue by nightdeveloper** [FarGroup/Far-NetBox#9]
While copying files, window move/resize leads to broken interface all time file coping...

Reproduce steps:
1. Create sftp connection to server;
2. Copy any larga file to local/remote server;
3. Move window to another monitor with different resolution/size/scale, interface is broken. Far default behavior - interface is not broken.

**Comment by alabuzhev** [comment]
Moved to https://github.com/michaellukashov/Far-NetBox/issues/379
